### ISSUE TITLE
let g:gruvbox_bold = 0 caused error E418: Illegal value: blend=NONE

### ISSUE THREAD

**Issue by ttys3** [npxbr/gruvbox.nvim#30]
`let g:gruvbox_bold = 0` caused error `E418: Illegal value: blend=NONE`

```
Error detected while processing /.local/share/nvim/plugged/gruvbox.nvim/colors/gruvbox.vim:
line    2:
E5108: Error executing lua ....local/share/nvim/plugged/lush.nvim/lua/lush.lua:62: Vim(highlight):E418: Illegal value: blend=NONE
```

the cause:

```vim
highlight TSStrong guifg=NONE guibg=NONE guisp=NONE gui= blend=NONE

highlight clojureRegexpCharClass guifg=#BDAF93 guibg=NONE guisp=NONE gui= blend=NONE

highlight htmlBold guifg=#EBDBB2 guibg=NONE guisp=NONE gui= blend=NONE

highlight WildMenu guifg=#83A598 guibg=#4F4945 guisp=NONE gui= blend=NONE

highlight Bold guifg=NONE guibg=NONE guisp=NONE gui= blend=NONE

highlight LspSagaRenameBorder guifg=NONE guibg=NONE guisp=NONE gui= blend=NONE
```

@npxbr maybe we should fix this in the upstream ?

https://github.com/rktjmp/lush.nvim/blob/8f03467d6dbb6c24cfa5ebe538ec873f9d4235bb/lua/lush/compiler.lua#L23

like this :

```lua

  local gui = opts.gui or 'NONE'
  gui = string.gsub(gui, ' ', '')
  if gui == '' then
	gui = 'NONE'
  end

```

https://github.com/ttys3/lush.nvim/commit/34e2cf62b86eae265acf521e0f2a6879982a68c0

or ? we should not put `gui` to the `highlight` command if `gui` is empty string ?

**Comment by ttys3** [comment]
there's another problem:

```vim
highlight htmlBoldUnderline guifg=#EBDBB2 guibg=NONE guisp=NONE gui=,underline blend=NONE
```

the `gui=,underline`

even we have `gui == ''` detection in the upstream, this still a problem

**Comment by rktjmp** [comment]
I think it's the theme writers responsibility to provide well formed values in the spec, and such ttys3/lush.nvim@8f1bbed very likely not be accepted.

(I don't mean that to sound hash, it's just that it soon becomes, "why doesn't lush prefix my colors with #?", "why doesn't lush clamp my blend value to 0-100?",  "why doesn't lush use the new :: join syntax", etc. At some point the user is responsible for writing valid syntax.)

The compiler translating empty strings to NONE (while I have included a patch upstream, for now) is already a stretch to me, IMO you should not provide the key if you do not want to set a value.

The `''` patch is **already brittle** because it will fail in the same manner if you provide `gui = '      '` in your spec.

I might add a check for that but I can already see the case where someone does `table.concat({nil_value, nil_value, nil_value}, ",") => ",,"` and then thinks, well Lush already saves me from `''` and `'bold, italic'` (maybe already a design mistake), why can't it save me here? Basically, it the error correction isn't comprehensive enough to catch 99%, I am not keen to catch 5%. It encourages sloppy practices and makes the tool fuzzier to reason with.

Future versions of Lush may raise an error on empty strings in the parser. I encourage you to correctly form values. Use nil for an empty value.

You can avoid most of the issues here by just collecting your `options => value` pairs and `table.concat(values, ",")` them instead of building the string piece meal.

**Comment by dhruvmanila** [comment]
I was facing the same issue and I started debugging it as well. It turned out that setting the `gui` field to an empty string caused the error and changing it to `NONE`, if not given, resolved it.

Also, the original option contained `g:gruvbox_sign_column` to provide a custom color for the sign column but that setting is absent in here. (https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_sign_column). If I am missing it, then my bad :)

Another thing I noticed is that the logic for configuring colors using some of the options like `gruvbox_hls_cursor` seems to be broken:
- Instead of using the gruvbox color names, we would have to use the names provided in the `colors` table in this file: https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/colors.lua#L4 as that's how the code gets the color: https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/init.lua#L136
- That's another problem because what we get is a table and the `hsl` function expects either a `string` or `number, number, number`. The solution is simple: remove the call to `hsl` function.
```
Error in packer_compiled: Vim(lua):E5108: Error executing lua .../.config/nvim/lua/plugin/
colorscheme.lua:28: Vim(lua):E5108: Error executing lua ...site/pack/packer/start/gruvbox.nvim/lua/gruvbox
/init.lua:142: hsl() expects (number, number, number) or (string)
```

**Comment by rktjmp** [comment]
Not really responding to anyone in particular, but have you considered dropping the old gruvbox configuration for a lua one? Probably let you avoid a bunch of headaches.

Obviously this removes the "drop in replacement" checkbox so it may not be ideal, depends on your goals.

You could probably even specify just do it all via lush.extends or use that after processing the users config table (probably better out of the box UX).

**Comment by rktjmp** [comment]
@dhruvmanila 

> Another thing I noticed is that the logic for configuring colors using some of the options like `gruvbox_hls_cursor` seems to be broken:
> 
> * Instead of using the gruvbox color names, we would have to use the names provided in the `colors` table in this file: https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/colors.lua#L4 as that's how the code gets the color: https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/init.lua#L136
> 
> * That's another problem because what we get is a table and the `hsl` function expects either a `string` or `number, number, number`. The solution is simple: remove the call to `hsl` function.

That seems like you just need to add the gruvbox color names to the colors table?

i.e:

```
colors = {
  bg1 = '#....',
}
```

Then it would just work?

**Comment by dhruvmanila** [comment]
No, I think what the author is doing is making a base table consisting of colors for both the dark and light background. The implementation should be changed such that even if we move from the original version of gruvbox to the lua version, as the options are the same, the user should not need to change the configuration.

This requires to change the code where the user options are used to update colors. An example:
```lua
-- https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/init.lua#L135
if vim.g.gruvbox_hls_cursor ~= nil then
  hls_cursor = hsl(colors[vim.g.gruvbox_hls_cursor])
end
```
The main problem is we cannot set different color for options like `gruvbox_hls_cursor`, `gruvbox_hls_highlight`, `gruvbox_number_column`, etc. as it raises the above error. The fix for that is not to call the `hsl` function [in here](https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/init.lua#L136) as it was already called in the `colors` table.

**Comment by rktjmp** [comment]
Ah yes sorry, I didn't use my brain. The colours are already hsl'd.

**Comment by ttys3** [comment]
@rktjmp thanks for the very detailed and useful comment

I tried make this change: https://github.com/ttys3/gruvbox.nvim/blob/6b141f330db7147c08148f2449a85e1bb61fc1b2/lua/gruvbox/init.lua#L356

but failed with error:

```
Error detected while processing .../.local/share/nvim/plugged/gruvbox.nvim/colors/gruvbox.vim:
line    2:
E5108: Error executing lua ...cal/share/nvim/plugged/gruvbox.nvim/lua/gruvbox/init.lua:356: attempt to call field 'concat' (a nil value)
```

**Comment by rktjmp** [comment]
Because of how lua/lush works you have to alias concat to use it in spec, or do it beforehand:

https://github.com/rktjmp/lush.nvim/blob/main/examples/module-injection/lua/lush_theme/module_injection.lua

```lua
local table_concat = table.concat
local groups = lush(function()
  return {
    Error {GruvboxRed, gui = table_concat({styles.bold, styles.underline}, ",")
},
  }
end)
```
or
```lua
local error_gui  = table.concat({styles.bold, styles.underline}, ",")
local groups = lush(function()
  return {
    Error {GruvboxRed, gui = error_gui},
  }
end)
``` 
Globals aren't imported (too messy, might conflict with group names or whatever), so the lush spec namespace is limited to whats scoped to the file.

You could also do something like, though maybe not 100% appropriate. There's more examples of how this might work in the docs/readme under advanced usage if you wanted to modularise configuration.

```lua
local groups = lush(function()
  return {
  -- ...
  }
end)

local xxx = {groups}
 
-- could be in a different file
if config.errors.italic then
  italic_errors = lush.parse(function()
    return {
      Error { groups.Error, gui = "italic" }
    }
  end)
  xxx = table.append(xxx, italic_errors) 
end

lush.merge(xxx)
```

**Comment by ellisonleao** [comment]
yeah the current code is still not using the new `merge` spec. I hope to make all the fixes and updates ASAP. Thanks for the insights guys

**Comment by ellisonleao** [comment]
@ttys3 can you share your custom config please?

@dhruvmanila can you share yours as well please?

**Comment by ttys3** [comment]
Got the `table.concat` problem fixed in https://github.com/ttys3/gruvbox.nvim/commit/d513bc892df99e50507ad89fd8ca7baa9634827a

but another small problem, for example:

`htmlBoldUnderline {fg = fg1, gui = table_concat({styles.bold, styles.underline}, ",")},`

if `styles.bold` is set to `NONE`, then the result `highlight` cmd will like:

```vim
highlight htmlBoldUnderline guifg=#EBDBB2 guibg=NONE guisp=NONE gui=NONE,underline blend=NONE
``
it is very strange to have `gui=NONE,underline` here, although neovim does not complain now.

**Comment by ttys3** [comment]
> @ttys3 can you share your custom config please?
> 
> @dhruvmanila can you share yours as well please?

here

```vim
let g:gruvbox_bold = 0
let g:gruvbox_italic = 1
let g:gruvbox_contrast_dark = 'soft'
colorscheme gruvbox
```

**Comment by rktjmp** [comment]
@ttys3 

given `htmlBoldUnderline {fg = fg1, gui = table_concat({styles.bold, styles.underline}, ",")},`

If `styles.bold = 'NONE'`, & `styles.underline = 'underline'`

then

`table_concat({styles.bold, styles.underline}, ",")`

is

`table_concat({'NONE', 'underline'}, ",") = NONE,underline`

It's doing what you ask of it.

**Comment by ellisonleao** [comment]
not that you guys asked, but i will be working on those issues tomorrow in stream @ twitch.tv/npxbr 10AM GMT-3

**Comment by ellisonleao** [comment]
hey @ttys3 i just tested your config here and it seems to be working now, can you pull latest and check again, please?

**Comment by ellisonleao** [comment]
hey @dhruvmanila i've fixed the custom vars for those colors, can you test it again please?

Also, i don't see a `g:gruvbox_transparent_bg` config in the original gruvbox-community code. Does that config exists somewhere else?

**Comment by dhruvmanila** [comment]
@ellisonleao yes, it is working now. Thank you for fixing it.

It seems that the gruvbox-community does not provide the option `g:gruvbox_transparent_bg` but the [original gruvbox does](https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_transparent_bg).

**Comment by ellisonleao** [comment]
@dhruvmanila that setting doesn't appears to have any effect since i can't find it in the codebase anywhere. Are you getting any transparency?

**Comment by ttys3** [comment]
> hey @ttys3 i just tested your config here and it seems to be working now, can you pull latest and check again, please?

The latest version works like a charm

**Comment by ellisonleao** [comment]
closing this since the bug was fixed

**Comment by dhruvmanila** [comment]
Right. The original gruvbox code does not contain the use of that option although I used [gruvbox-material](https://github.com/sainnhe/gruvbox-material) which has the same option and what it does is basically remove any background color like in the the sign column.

Ref (`*_transparent_bg`): https://github.com/sainnhe/gruvbox-material/blob/master/colors/gruvbox-material.vim#L31
